[package]
name = "spaceship"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.13.0", features = ["wav"] }
fastrand = "2.0.1"
winit = { version = "0.29.10", default-features = false }
